#!/usr/bin/env bash

temp=$(mktemp -d)
trap 'rm -rf "$temp"' EXIT

git clone --depth=1 https://github.com/cmus/cmus "$temp"

sudo pacman -S --needed \
	pkg-config ncurses libiconv faad2 alsa-lib libao libcddb libcdio-paranoia \
	libdiscid ffmpeg flac jack libmad libmodplug libmp4v2 libmpcdec opusfile \
	libpulse libsamplerate libvorbis wavpack

cd "$temp"
./configure
sudo make install
