alias ls="ls --color=auto"
alias grep="grep --color=auto"
alias ip="ip -c=auto"
alias la="ls -A"
alias ll="ls -l"
alias lh="ll -h"
alias lah="la -lh"
alias mv="mv -iv"
alias cp="cp -iv"
alias mkdir="mkdir -vp"
alias less="less -igmj .5"
alias copy="xclip -se c"
alias ru="setxkbmap ru"
alias у="setxkbmap us" # U+0443 CYRILLIC SMALL LETTER U
alias yay="PKGEXT=.pkg.tar yay" # skip compression
alias whois="whois -H"
alias history="history 1"
alias diff="diff --color=auto"
alias shred="shred -vzu"
alias mirrors="sudo reflector --verbose --country DE,GB,US --protocol https --sort rate --latest 20 --save /etc/pacman.d/mirrorlist"
alias http="python -m http.server"
