alias ls="ls --color=auto"
alias grep="grep --color=auto"
alias la="ls -A"
alias ll="ls -l"
alias lh="ll -h"
alias lah="la -lh"
alias mv="mv -iv"
alias cp="cp -iv"
alias mkdir="mkdir -vp"
alias less="less -igmj .5"
alias copy="xclip -se c"
alias ru="setxkbmap 'ru'"
alias у="setxkbmap 'us'"
alias yay="PKGEXT=.pkg.tar yay" # skip compression
alias whois="whois -H"
alias history="history 1"
alias diff="diff --color=auto -u"
alias shred="shred -vzu"
alias temp="awk '{print \$1/1000 \"°C\"}' /sys/class/thermal/thermal_zone0/temp"
alias mirrors="sudo reflector --verbose --country DE,GB,US --protocol https --sort rate --latest 20 --save /etc/pacman.d/mirrorlist"
alias http="python -m http.server"
alias gitopen="xdg-open \$(git remote get-url origin)"
