package main

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"time"

	"roe/sb/constants"
	"roe/sb/util"
)

func main() {
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		panic("runtime.Caller failed")
	}
	name := filepath.Join(filepath.Dir(file), "../../components/volume_pulse.h")
	f, err := os.Create(name)
	if err != nil {
		util.Warn("%v", err)
		os.Exit(1)
	}
	defer f.Close()

	write := func(format string, a ...any) {
		s := fmt.Sprintf(format, a...)
		fmt.Printf("%q >> %s\n", s, name)
		f.WriteString(s)
	}

	write("// Code generated by 'gen_volume_pulse_constants'. DO NOT EDIT.\n")
	write("#pragma once\n\n")

	write("#define CLIENT_NAME %q\n\n",
		constants.VolumePulseClientName)

	write("#define INITIAL_RETRY_DELAY_US %d\n",
		constants.VolumeInitialRetryDelay/time.Microsecond)
	write("#define MAX_RETRY_DELAY_US     %d\n",
		constants.VolumeMaxRetryDelay/time.Microsecond)
}
